spring.application.name=Study-Center


    spring.datasource.url=jdbc:mysql://localhost:3306/aabhyasika

spring.datasource.username=root
spring.datasource.password=Rajesh#1435
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.format_sql=true



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rajeshgahilod1435@gmail.com
spring.mail.password=lpex duxu ghws kjyb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.key=rzp_test_SA1Y2HXyFwaozZ
razorpay.secret=9uIWiqLutgLRI6hF06ne3IBS
spring.jpa.open-in-view=false

#razorpay.key.id=rzp_test_SA1Y2HXyFwaozZ
#razorpay.key.secret=9uIWiqLutgLRI6hF06ne3IBS

server.port=${PORT:8080}
